apiVersion: v1
entries: 
  sn-platform:
  - apiVersion: v1
    appVersion: 3.0.0
    created: "2023-09-18T07:37:19.52128363Z"
    dependencies:
    - condition: monitoring.loki
      name: loki-stack
      repository: https://grafana.github.io/helm-charts
      version: 0.36.1
    description: StreamNative Platform Chart
    digest: 65ae3f97f8398d77a73be8dba60da9e70cbad024aa4aeb8c599aca4fa1820b1b
    home: https://streamnative.io
    icon: https://raw.githubusercontent.com/streamnative/charts/master/static/logo.svg
    maintainers:
    - email: support@streamnative.io
      name: StreamNative Support
    name: sn-platform
    sources:
    - https://github.com/streamnative/charts/tree/master/charts/sn-platform
    urls:
    - https://github.com/streamnative/charts/releases/download/sn-platform-1.11.0/sn-platform-1.11.0.tgz
    version: 1.11.0